# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            ProtoBuf
tagline:          'Protocol Buffers in C# code'
description:      'C# Code Generator'
url:              https://silentorbit.com/protobuf
baseurl:          /protobuf
email:		hello@silentorbit.com

author:
  name:           'Peter Hultqvist'
  url:            https://silentorbit.com/hultqvist/

license:
  url:		https://www.apache.org/licenses/LICENSE-2.0
  title:	Apache License 2.0

paginate:         5
paginate_path:    "/updates/page:num"

# Custom vars
version:          1.2.3

github:
  repo:           https://github.com/hultqvist/protobuf
  page:           https://github.com/hultqvist/protobuf/tree/gh-pages
  branch:         gh-pages
